name: Github Actions Tests

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Load pkl version
        id: load-pkl-version
        run: |
          PKL_VERSION=$(cat .pkl-version)
          echo "PKL_VERSION=${PKL_VERSION}" >> "$GITHUB_OUTPUT"
      - name: Install pkl
        env:
          PKL_VERSION: ${{ steps.load-pkl-version.outputs.PKL_VERSION }}
        run: |
          curl -L -o pkl https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-linux-amd64
          chmod u+x pkl
      - name: Validate Task Config
        run: |
          set -o pipefail
          ./pkl eval tests/task-config.pkl | diff tests/expected/task-config.yml -
      - name: Validate Pipeline Config
        run: |
          set -o pipefail
          ./pkl eval tests/pipeline.pkl | diff tests/expected/pipeline.yml -
      - name: Validate package can build
        run: |
          ./pkl project package src/ --output-path build/
